# Generated by Django 5.1.5 on 2025-03-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('perex', models.TextField()),
                ('image', models.URLField()),
                ('creation', models.TextField()),
                ('singer', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
