# Generated by Django 5.1.5 on 2025-05-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_genre_singer_rename_article_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
