# Generated by Django 5.1.5 on 2025-05-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_singer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
